# Generated by Django 6.0.1 on 2026-02-03 14:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_emoji', models.CharField(blank=True, max_length=10)),
                ('quantity_added', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user_name', models.CharField(max_length=100)),
                ('restock_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_records', to='api.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_restock_record',
                'ordering': ['-restock_date'],
                'indexes': [models.Index(fields=['product'], name='api_restock_product_372127_idx'), models.Index(fields=['restock_date'], name='api_restock_restock_c76079_idx'), models.Index(fields=['user'], name='api_restock_user_id_237d1f_idx')],
            },
        ),
    ]
