# Generated by Django 6.0.1 on 2026-02-04 13:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_quantity_alter_saleitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Developer', 'Developer'), ('Admin', 'Admin'), ('Moderator', 'Moderator'), ('User', 'User')], default='User', help_text='User role for access control', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Employee's monthly salary for payroll calculations", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Overtime multiplier for calculating overtime pay (e.g., 1.5 for time and a half)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'api_userprofile',
                'ordering': ['user__username'],
            },
        ),
    ]
