# Generated by Django 6.0.1 on 2026-02-04 22:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Admin', 'Admin'), ('Moderator', 'Moderator'), ('Employee', 'Employee'), ('Seller', 'Seller')], default='Seller', help_text='User role for access control', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('General', 'General'), ('Supplies', 'Supplies'), ('Travel', 'Travel'), ('Meals', 'Meals'), ('Equipment', 'Equipment'), ('Other', 'Other')], default='General', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_attendance_expense',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'expense_date'], name='api_attenda_user_id_a9e86e_idx'), models.Index(fields=['expense_date'], name='api_attenda_expense_f3a9c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Reset', 'Reset'), ('AbsentWithPermission', 'Absent With Permission'), ('AbsentWithoutPermission', 'Absent Without Permission')], default='Present', max_length=30)),
                ('is_present', models.BooleanField(default=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('daily_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('absence_permission_type', models.CharField(choices=[('None', 'None'), ('WithPermission', 'With Permission'), ('WithoutPermission', 'Without Permission'), ('Reset', 'Reset')], default='None', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_attendance_record',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_attenda_user_id_05018a_idx'), models.Index(fields=['date'], name='api_attenda_date_86fd05_idx'), models.Index(fields=['status'], name='api_attenda_status_de03a4_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('month', models.DateField()),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('total_regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_payroll', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expenses_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rest_day_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('absence_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_attendance_summary',
                'ordering': ['-month', 'user_name'],
                'indexes': [models.Index(fields=['user', 'month'], name='api_attenda_user_id_b30a45_idx'), models.Index(fields=['month'], name='api_attenda_month_d11d5e_idx')],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
