# Generated by Django 6.0.1 on 2026-02-05 01:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_attendance_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('new_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('old_overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('new_overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
                ('changed_by_name', models.CharField(blank=True, max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='api.userprofile')),
            ],
            options={
                'db_table': 'api_salary_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user_profile', 'changed_at'], name='api_salary__user_pr_c73c82_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('sale', 'Create Sale'), ('restock', 'Restock Product'), ('attendance', 'Attendance Action'), ('expense', 'Expense Action'), ('password_change', 'Password Change'), ('role_change', 'Role Change'), ('salary_change', 'Salary Change'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_activity_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_user_ac_user_id_82f996_idx'), models.Index(fields=['activity_type', 'timestamp'], name='api_user_ac_activit_28b0e6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='api_user_ac_resourc_5a9b11_idx')],
            },
        ),
    ]
