# Generated by Django 6.0.1 on 2026-02-06 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_salary_history_and_activity_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('work_to_rest_ratio', models.IntegerField(default=6, help_text='Number of days worked to earn 1 rest day (default: 6)')),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
                'db_table': 'shop_settings',
            },
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='rest_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'quantity'], name='api_product_is_acti_95c1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at', 'status'], name='api_sale_created_ac211c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='api_sale_custome_560c74_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['staff'], name='api_sale_staff_i_117ba4_idx'),
        ),
    ]
